grails-app/controllers/biz/nellemann/powerdns/ZoneController.groovy
/**
 *   Copyright (C) 2014  Mark Nellemann <mark.nellemann@gmail.com>
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package biz.nellemann.powerdns

import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Transactional(readOnly = true)
@Secured(['ROLE_ADMIN', 'ROLE_USER'])
class ZoneController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def springSecurityService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)

        // Get list of domains belonging to logged-in user
        def user = User.get(springSecurityService.principal.id)
        def result = Zone.createCriteria().list(params) {
            eq('user', user)
        }

        respond(result, model:[ zoneInstanceCount: Zone.findAllByUser(user).size() ])
    }


    def suspendItem(Zone zoneInstance) {

        // We make sure the domain exists and is owned by the logged-in user
        def d = Zone.findByIdAndUser(zoneInstance?.id, springSecurityService.currentUser)
        if(d == null) {
            notFound()
            return
        }

        zoneInstance.active = false
        zoneInstance.save(flush:true)

        def result = Zone.findAllByUser(springSecurityService.currentUser)
        render(template: 'list', model: [zoneInstanceCount: result.size(), zoneInstanceList: result])
    }

    def releaseItem(Zone zoneInstance) {

        // We make sure the domain exists and is owned by the logged-in user
        def d = Zone.findByIdAndUser(zoneInstance?.id, springSecurityService.currentUser)
        if(d == null) {
            notFound()
            return
        }

        zoneInstance.active = true
        zoneInstance.save(flush:true)

        def result = Zone.findAllByUser(springSecurityService.currentUser)
        render(template: 'list', model: [zoneInstanceCount: result.size(), zoneInstanceList: result])
    }

    def show(Zone zoneInstance) {

        // We make sure the domain exists and is owned by the logged-in user
        def d = Zone.findByIdAndUser(zoneInstance?.id, springSecurityService.currentUser)
        if(d == null) {
            notFound()
            return
        }

        respond zoneInstance
    }

    def create() {
        respond new Zone(params)
    }

    @Transactional
    def save(Zone zoneInstance) {
        if (zoneInstance == null) {
            notFound()
            return
        }

        // Validate domains
        if (zoneInstance.hasErrors()) {
            respond zoneInstance.errors, view:'create'
            return
        }

        // Add domain to logged-in user
        def user = User.find(springSecurityService.currentUser)
        user.addToZones(zoneInstance)

        // Save the domain
        zoneInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'zoneInstance.label', default: 'Zone'), zoneInstance.id])
                redirect action: "index", method: "GET" //zoneInstance
            }
            '*' { respond zoneInstance, [status: CREATED] }
        }
    }

    def edit(Zone zoneInstance) {

        // Lookup domain provided in request
        if (zoneInstance == null) {
            notFound()
            return
        }

        // We make sure the domain exists and is owned by the logged-in user
        def d = Zone.findByIdAndUser(zoneInstance?.id, springSecurityService.currentUser)
        if(d == null) {
            notFound()
            return
        }

        respond zoneInstance
    }

    @Transactional
    def update(Zone zoneInstance) {

        if (zoneInstance == null) {
            notFound()
            return
        }

        // We make sure the domain exists and is owned by the logged-in user
        def d = Zone.findByIdAndUser(zoneInstance?.id, springSecurityService.currentUser)
        if(d == null) {
            notFound()
            return
        }

        // Validate domain
        if (zoneInstance.hasErrors()) {
            respond zoneInstance.errors, view:'edit'
            return
        }

        zoneInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Zone.label', default: 'Zone'), zoneInstance.id])
                redirect action: "index", method: "GET" //zoneInstance
            }
            '*'{ respond zoneInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Zone zoneInstance) {

        if (zoneInstance == null) {
            notFound()
            return
        }

        // We make sure the domain exists and is owned by the logged-in user
        def d = Zone.findByIdAndUser(zoneInstance?.id, springSecurityService.currentUser)
        if(d == null) {
            notFound()
            return
        }

        // Delete the domain
        zoneInstance.delete(flush:true)

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Zone.label', default: 'Zone'), zoneInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'zoneInstance.label', default: 'Zone'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>PowerDNS Admin - <g:layoutTitle/></title>
    <r:require modules="bootstrap,jquery"/>
    <link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" />
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}" />
    <r:layoutResources/>
    <tooltip:resources/>
</head>
<body style="padding-top: 60px; padding-bottom: 15px; padding-left: 5px; padding-right: 5px;">

<!-- Navigation -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation" data-role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="${createLink(uri: '/')}">PowerDNS Admin</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <!-- Home -->
                <li><a href="${createLink(uri: '/home')}"><span class="glyphicon glyphicon-home"></span> Home</a></li>

                <!-- Zones -->
                <sec:ifLoggedIn>
                    <li><g:link controller="zone" action="index"><span class="glyphicon glyphicon-list"></span> Zones</g:link></li>
                </sec:ifLoggedIn>

                <!-- Templates -->
                <sec:ifLoggedIn>
                    <!--<li><g:link controller="template" action="index"><span class="glyphicon glyphicon-list-alt"></span> Templates</g:link></li>-->
                </sec:ifLoggedIn>

                <!-- SuperMasters -->
                <sec:ifAllGranted roles="ROLE_ADMIN">
                    <li><g:link controller="superMaster" action="index"><span class="glyphicon glyphicon-flash"></span> SuperMasters</g:link></li>
                </sec:ifAllGranted>

                <!-- Users -->
                <sec:ifAllGranted roles="ROLE_ADMIN">
                <li><g:link controller="user" action="search"><span class="glyphicon glyphicon-user"></span> Accounts</g:link></li>
                </sec:ifAllGranted>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <sec:ifNotLoggedIn>
                    <li><g:link controller='login' action='auth'><span class="glyphicon glyphicon-info-sign"></span> Login</g:link></li></sec:ifNotLoggedIn>
                <sec:ifLoggedIn>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-info-sign"></span> <sec:username/><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><g:link controller="profile" action="edit">Profile</g:link></li>
                            <li><a href="#">Settings</a></li>
                            <li><g:link controller='logout'>Sign out</g:link></li>
                        </ul>
                    </li>
                </sec:ifLoggedIn>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<!-- Begin page content -->
<div class="container">

    <!-- Content -->
    <g:layoutBody/>

</div> <!-- /container -->


<r:layoutResources/>

</body>
</html>

grails-app/views/layouts/register.gsp
<html>

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title><g:layoutTitle default='User Registration'/></title>

<link rel="shortcut icon" href="${resource(dir:'images',file:'favicon.ico')}" type="image/x-icon"/>

<s2ui:resources module='register' />
<%--

The 'resources' tag in SecurityUiTagLib renders these tags if you're not using the resources plugin:

	<g:javascript library='jquery' plugin='jquery' />
	<link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'reset.css',plugin:'spring-security-ui')}"/>
	<link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'spring-security-ui.css',plugin:'spring-security-ui')}"/>
	<jqui:resources />
	<link rel="stylesheet" media="screen" href="${resource(dir:'css/smoothness',file:'jquery-ui-1.10.3.custom.css',plugin:'spring-security-ui')}"/>
	<link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'jquery.jgrowl.css',plugin:'spring-security-ui')}"/>
	<link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'jquery.safari-checkbox.css',plugin:'spring-security-ui')}"/>
	<link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'auth.css',plugin:'spring-security-ui')}"/>

or these if you are:

   <r:require module="register"/>
   <r:layoutResources/>

If you need to customize the resources, replace the <s2ui:resources> tag with
the explicit tags above and edit those, not the taglib code.
--%>

<g:layoutHead/>

</head>

<body>

<s2ui:layoutResources module='register' />
<g:layoutBody/>
<%--
<g:javascript src='jquery/jquery.jgrowl.js' plugin='spring-security-ui'/>
<g:javascript src='jquery/jquery.checkbox.js' plugin='spring-security-ui'/>
<g:javascript src='spring-security-ui.js' plugin='spring-security-ui'/>
--%>

<s2ui:showFlash/>

</body>
</html>

grails-app/views/layouts/springSecurityUI.gsp
<%@ page import="org.codehaus.groovy.grails.plugins.PluginManagerHolder" %>
<%@ page import="grails.plugin.springsecurity.SpringSecurityUtils" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title><g:layoutTitle default='Security Management Console'/></title>

    <link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon"/>

    <s2ui:resources module='spring-security-ui'/>
    <%--

    The 'resources' tag in SecurityUiTagLib renders these tags if you're not using the resources plugin:

       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'reset.css',plugin:'spring-security-ui')}"/>
       <g:javascript library='jquery' plugin='jquery' />
       <jqui:resources />
       <link rel="stylesheet" media="screen" href="${resource(dir:'css/smoothness',file:'jquery-ui-1.10.3.custom.css',plugin:'spring-security-ui')}"/>
       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'jquery.jgrowl.css',plugin:'spring-security-ui')}"/>
       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'jquery.safari-checkbox.css',plugin:'spring-security-ui')}"/>
       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'date_input.css',plugin:'spring-security-ui')}"/>
       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'jquery.jdMenu.css',plugin:'spring-security-ui')}"/>
       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'jquery.jdMenu.slate.css',plugin:'spring-security-ui')}"/>
       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'table.css',plugin:'spring-security-ui')}"/>
       <link rel="stylesheet" media="screen" href="${resource(dir:'css',file:'spring-security-ui.css',plugin:'spring-security-ui')}"/>

    or these if you are:

       <r:require module="spring-security-ui"/>
       <r:layoutResources/>

    If you need to customize the resources, replace the <s2ui:resources> tag with
    the explicit tags above and edit those, not the taglib code.
    --%>

    <%-- tab icons --%>
    <style>
    .icon_role {
        background-image: url('${fam.icon(name: 'lock')}');
    }

    .icon_users {
        background-image: url('${fam.icon(name: 'group')}');
    }

    .icon_user {
        background-image: url('${fam.icon(name: 'user')}');
    }

    .icon_error {
        background-image: url('${fam.icon(name: 'exclamation')}');
    }

    .icon_info {
        background-image: url('${fam.icon(name: 'information')}');
    }

    .icon, .ui-tabs .ui-tabs-nav li a.icon {
        background-repeat: no-repeat;
        padding-left: 24px;
        background-position: 4px center;
    }
    </style>

    <g:layoutHead/>

</head>

<body>

<div>

    <div>

        <ul class="jd_menu jd_menu_slate">
            <li><a class="accessible"><g:message code="spring.security.ui.menu.users"/></a>
                <ul>
                    <li><g:link controller="user" action='search'><g:message
                            code="spring.security.ui.search"/></g:link></li>
                    <li><g:link controller="user" action='create'><g:message
                            code="spring.security.ui.create"/></g:link></li>
                </ul>
            </li>
            <li><a class="accessible"><g:message code="spring.security.ui.menu.roles"/></a>
                <ul>
                    <li><g:link controller="role" action='search'><g:message
                            code="spring.security.ui.search"/></g:link></li>
                    <li><g:link controller="role" action='create'><g:message
                            code="spring.security.ui.create"/></g:link></li>
                </ul>
            </li>
            <g:if test='${SpringSecurityUtils.securityConfig.securityConfigType?.toString() == 'Requestmap'}'>
                <li><a class="accessible"><g:message code="spring.security.ui.menu.requestmaps"/></a>
                    <ul>
                        <li><g:link controller="requestmap" action='search'><g:message
                                code="spring.security.ui.search"/></g:link></li>
                        <li><g:link controller="requestmap" action='create'><g:message
                                code="spring.security.ui.create"/></g:link></li>
                    </ul>
                </li>
            </g:if>
            <g:if test='${SpringSecurityUtils.securityConfig.rememberMe.persistent}'>
                <li><a class="accessible"><g:message code="spring.security.ui.menu.persistentLogins"/></a>
                    <ul>
                        <li><g:link controller="persistentLogin" action='search'><g:message
                                code="spring.security.ui.search"/></g:link></li>
                    </ul>
                </li>
            </g:if>
            <li><a class="accessible"><g:message code="spring.security.ui.menu.registrationCode"/></a>
                <ul>
                    <li><g:link controller="registrationCode" action='search'><g:message
                            code="spring.security.ui.search"/></g:link></li>
                </ul>
            </li>
            <g:if test="${PluginManagerHolder.pluginManager.hasGrailsPlugin('springSecurityAcl')}">
                <li><a class="accessible"><g:message code="spring.security.ui.menu.acl"/></a>
                    <ul>
                        <li><g:message code="spring.security.ui.menu.aclClass"/> &raquo;
                            <ul>
                                <li><g:link controller="aclClass" action='search'><g:message
                                        code="spring.security.ui.search"/></g:link></li>
                                <li><g:link controller="aclClass" action='create'><g:message
                                        code="spring.security.ui.create"/></g:link></li>
                            </ul>
                        </li>
                        <li><g:message code="spring.security.ui.menu.aclSid"/> &raquo;
                            <ul>
                                <li><g:link controller="aclSid" action='search'><g:message
                                        code="spring.security.ui.search"/></g:link></li>
                                <li><g:link controller="aclSid" action='create'><g:message
                                        code="spring.security.ui.create"/></g:link></li>
                            </ul>
                        </li>
                        <li><g:message code="spring.security.ui.menu.aclObjectIdentity"/> &raquo;
                            <ul>
                                <li><g:link controller="aclObjectIdentity" action='search'><g:message
                                        code="spring.security.ui.search"/></g:link></li>
                                <li><g:link controller="aclObjectIdentity" action='create'><g:message
                                        code="spring.security.ui.create"/></g:link></li>
                            </ul>
                        </li>
                        <li><g:message code="spring.security.ui.menu.aclEntry"/> &raquo;
                            <ul>
                                <li><g:link controller="aclEntry" action='search'><g:message
                                        code="spring.security.ui.search"/></g:link></li>
                                <li><g:link controller="aclEntry" action='create'><g:message
                                        code="spring.security.ui.create"/></g:link></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </g:if>
            <li><a class="accessible"><g:message code="spring.security.ui.menu.appinfo"/></a>
                <ul>
                    <li><g:link action='config' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.config'/></g:link></li>
                    <li><g:link action='mappings' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.mappings'/></g:link></li>
                    <li><g:link action='currentAuth' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.auth'/></g:link></li>
                    <li><g:link action='usercache' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.usercache'/></g:link></li>
                    <li><g:link action='filterChain' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.filters'/></g:link></li>
                    <li><g:link action='logoutHandler' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.logout'/></g:link></li>
                    <li><g:link action='voters' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.voters'/></g:link></li>
                    <li><g:link action='providers' controller='securityInfo'><g:message
                            code='spring.security.ui.menu.appinfo.providers'/></g:link></li>
                </ul>
            </li>
        </ul>

        <div id='s2ui_header_body'>

            <div id='s2ui_header_title'>
                Spring Security Management Console
            </div>

            <span id='s2ui_login_link_container'>

                <nobr>
                    <div id='loginLinkContainer'>
                        <sec:ifLoggedIn>
                            Logged in as <sec:username/> (<g:link controller='logout'>Logout</g:link>)
                        </sec:ifLoggedIn>
                        <sec:ifNotLoggedIn>
                            <a href='#' id='loginLink'>Login</a>
                        </sec:ifNotLoggedIn>

                        <sec:ifSwitched>
                            <a href='${request.contextPath}/j_spring_security_exit_user'>
                                Resume as <sec:switchedUserOriginalUsername/>
                            </a>
                        </sec:ifSwitched>
                    </div>
                </nobr>

            </span>
        </div>

    </div>

    <div id="s2ui_main">
        <div id="s2ui_content">
            <s2ui:layoutResources module='spring-security-ui'/>
            <g:layoutBody/>
            <%--
            <g:javascript src='jquery/jquery.jgrowl.js' plugin='spring-security-ui'/>
            <g:javascript src='jquery/jquery.checkbox.js' plugin='spring-security-ui'/>
            <g:javascript src='jquery/jquery.date_input.js' plugin='spring-security-ui'/>
            <g:javascript src='jquery/jquery.positionBy.js' plugin='spring-security-ui'/>
            <g:javascript src='jquery/jquery.bgiframe.js' plugin='spring-security-ui'/>
            <g:javascript src='jquery/jquery.jdMenu.js' plugin='spring-security-ui'/>
            <g:javascript src='jquery/jquery.dataTables.min.js' plugin='spring-security-ui'/>
            <g:javascript src='spring-security-ui.js' plugin='spring-security-ui'/>
            --%>
        </div>
    </div>

</div>

<g:render template='/includes/ajaxLogin' plugin='spring-security-ui'/>

<s2ui:showFlash/>

</body>
</html>