grails-app/domain/biz/nellemann/powerdns/SuperMaster.groovy
/**
 *   Copyright (C) 2014  Mark Nellemann <mark.nellemann@gmail.com>
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package biz.nellemann.powerdns

/*
    This is slave auto provisioning
    We add known master nameservers, and if they notify us, pdns will add the slave zone

    Will this interfere with PowerDNS Admin ??


    To configure a supermaster with IP address 10.0.0.11 which lists this installation as 'autoslave.powerdns.com', issue the following:

	insert into supermasters ('10.0.0.11','autoslave.powerdns.com','internal');

    From now on, valid notifies from 10.0.0.11 that list a NS record containing 'autoslave.powerdns.com'
    will lead to the provisioning of a slave domain under the account 'internal'.
 */

class SuperMaster {

    def validationService

    String ip               // The IP address of the
    String nameserver       // The authorative nameserver for the domain
    String account = 'internal'

    static constraints = {
        ip(blank: false, unique: true, size: 1..46, validator: { val, obj -> return obj.validationService.validateIpAddress(val)})
        nameserver(blank: false, validator: { val, obj -> return obj.validationService.validateDomainName(val, false) }  )
        account(blank: true, nullable: true, size: 1..128 )
    }

    // GORM Database Mappings
    static mapping = {
        table 'supermasters'
        id generator: 'identity'
        version false
        autoTimestamp false
    }
}

grails-app/controllers/biz/nellemann/powerdns/SuperMasterController.groovy
/**
 *   Copyright (C) 2014  Mark Nellemann <mark.nellemann@gmail.com>
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package biz.nellemann.powerdns

import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Transactional(readOnly = true)
@Secured(['ROLE_ADMIN'])
class SuperMasterController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)

        def result = SuperMaster.list()
        respond(result, model:[ superMasterInstanceCount: result.size() ])
    }


    def show(SuperMaster superMasterInstance) {
        respond superMasterInstance
    }

    def create() {
        respond new SuperMaster(params)
    }


    @Transactional
    def save(SuperMaster superMasterInstance) {
        if (superMasterInstance == null) {
            notFound()
            return
        }

        // Validate superMaster
        if (superMasterInstance.hasErrors()) {
            respond superMasterInstance.errors, view:'create'
            return
        }

        // Save the instance
        superMasterInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'superMasterInstance.label', default: 'SuperMaster'), superMasterInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { respond superMasterInstance, [status: CREATED] }
        }
    }
           
    
    def edit(SuperMaster superMasterInstance) {

        // Lookup domain provided in request
        if (superMasterInstance == null) {
            notFound()
            return
        }

        respond superMasterInstance
    }

    @Transactional
    def update(SuperMaster superMasterInstance) {

        if (superMasterInstance == null) {
            notFound()
            return
        }

        // Validate domain
        if (superMasterInstance.hasErrors()) {
            respond superMasterInstance.errors, view:'edit'
            return
        }

        superMasterInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'SuperMaster.label', default: 'SuperMaster'), superMasterInstance.id])
                redirect action: "index", method: "GET" //superMasterInstance
            }
            '*'{ respond superMasterInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(SuperMaster superMasterInstance) {

        if (superMasterInstance == null) {
            notFound()
            return
        }

        // Delete it
        superMasterInstance.delete(flush:true)

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'supermaster.label', default: 'SuperMaster'), superMasterInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'supermaster.label', default: 'SuperMaster'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

}

grails-app/views/superMaster/_form.gsp
<%@ page import="biz.nellemann.powerdns.SuperMaster" %>

<!-- IP Address -->
<div class="form-group ${hasErrors(bean: superMasterInstance, field: 'ip', 'has-error')} required">
    <label class="col-xs-6 col-sm-4 col-md-4 col-lg-4 control-label" for="ip">
        <g:message code="supermaster.ip.label" default="IP Address"/>
        <span class="required-indicator">*</span>
    </label>
    <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
        <g:textField class="form-control" name="ip" required="" value="${superMasterInstance?.ip}" />
        <p class="help-block visible-md visible-lg">The IP address of the nameserver notifying us.</p>
    </div>
</div>

<!-- Nameserver -->
<div class="form-group ${hasErrors(bean: superMasterInstance, field: 'nameserver', 'has-error')} required">
    <label for="name" class="col-xs-6 col-sm-4 col-md-4 col-lg-4 control-label">
        <g:message code="supermaster.nameserver.label" default="Nameserver"/>
        <span class="required-indicator">*</span>
    </label>
    <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
        <g:textField class="form-control" name="nameserver" required="" value="${superMasterInstance?.nameserver}" />
        <p class="help-block visible-md visible-lg">Must be a valid NS record from the zones we are being slave of.</p>
    </div>
</div>

grails-app/views/superMaster/_list.gsp
<table class="table table-striped table-responsive table-hover">
    <thead>
    <tr>
        <g:sortableColumn property="ip" title="${message(code: 'supermaster.ip.label', default: 'IP Address')}"/>
        <g:sortableColumn property="nameserver" title="${message(code: 'supermaster.nameserver.label', default: 'Nameserver')}"/>
        <th>${message(code: 'domain.action.label', default: 'Actions')}</th>
    </tr>
    </thead>
    <tbody>
    <g:each in="${superMasterInstanceList}" status="i" var="superMasterInstance">
        <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
            <td>${fieldValue(bean: superMasterInstance, field: "ip")}</td>
            <td>${fieldValue(bean: superMasterInstance, field: "nameserver")}</td>
            <td>
                <tooltip:tip value="Edit domain">
                    <g:link action="edit" id="${superMasterInstance?.id}"><span class="glyphicon glyphicon-edit"></span></g:link>
                </tooltip:tip>
            </td>
        </tr>
    </g:each>
    </tbody>
</table>

grails-app/views/superMaster/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <r:require modules="bootstrap"/>
    <g:set var="entityName" value="${message(code: 'supermaster.label', default: 'SuperMaster')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>

<!-- Breadcrumbs -->
<div class="row">
    <ol class="breadcrumb">
        <li><g:link controller="superMaster" action="index">SuperMasters</g:link></li>
        <li class="active">New</li>
    </ol>
</div>

<!-- Header and Alerts -->
<div class="row">
    <g:if test="${flash.message}">
        <div class="alert alert-info" role="status">${flash.message}</div>
    </g:if>
</div>

<!-- Validation Errors -->
<g:hasErrors bean="${superMasterInstance}">
    <div class="row">
        <ul class="alert alert-danger" role="alert">
            <g:eachError bean="${superMasterInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </div>
</g:hasErrors>

<!-- Create Domain -->
<div class="row">
    <g:form class="form-horizontal" url="[resource:superMasterInstance, action:'save']" role="form">
        <g:hiddenField name="version" value="${superMasterInstance?.version}"/>
        <g:render template="form" />

        <div class="form-group">
            <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4"></div>
            <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4 pull-left">
                <g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                <g:link controller="superMaster" action="index"><button type="reset" class="btn">${message(code: 'default.button.cancel.label', default: 'Cancel')}</button></g:link>
            </div>
        </div>
    </g:form>
</div>

</body>
</html>

grails-app/views/superMaster/edit.gsp
<%@ page import="biz.nellemann.powerdns.SuperMaster" %>
<!DOCTYPE html>
<html>
<head>
    <g:set var="entityName" value="${message(code: 'supermaster.label', default: 'SuperMaster')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
    <meta name="layout" content="main">
    <r:require modules="bootstrap"/>
</head>
<body>

<!-- Breadcrumbs -->
<div class="row">
    <ol class="breadcrumb">
        <li><g:link controller="superMaster" action="index">SuperMasters</g:link></li>
        <li class="active">${superMasterInstance?.ip}</li>
    </ol>
</div>

<!-- Header and Alerts -->
<div class="row">
    <g:if test="${flash.message}">
        <div class="alert alert-info" role="status">${flash.message}</div>
    </g:if>
</div>


<!-- Validation Errors -->
<g:hasErrors bean="${superMasterInstance}">
    <div class="row">
        <ul class="alert alert-danger" role="alert">
            <g:eachError bean="${superMasterInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </div>
</g:hasErrors>


<!-- Edit/Update Form -->
<div class="row">

    <g:form id="updateForm" class="form-horizontal" url="[resource:superMasterInstance, action:'update']" method="PUT" role="form">
        <g:hiddenField name="version" value="${superMasterInstance?.version}"/>
        <g:render template="form" />
    </g:form>

</div>

<div class="row">
    <div class="form-group">
        <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4"></div>
        <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4 pull-left">
            <g:actionSubmit name="update" class="btn btn-primary" value="${message(code: 'default.button.update.label', default: 'Update')}" onclick="document.getElementById('updateForm').submit();" />
            <g:actionSubmit name="delete" class="btn btn-danger" value="${message(code: 'default.button.delete.label', default: 'Delete')}" data-toggle="modal" data-target="#deleteModal" />
            <g:link controller="superMaster" action="index"><button type="reset" class="btn">${message(code: 'default.button.cancel.label', default: 'Cancel')}</button></g:link>
        </div>
    </div>
</div>


<!-- Dialogs -->
<div id="deleteModal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Delete SuperMaster</h4>
            </div>
            <div class="modal-body">
                <p>This SuperMaster will be permanently deleted and cannot be recovered. Are you sure?</p>
                <g:form id="deleteForm" url="[resource:superMasterInstance, action:'delete']" method="DELETE"></g:form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="document.getElementById('deleteForm').submit();">Delete</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


</body>
</html>

grails-app/views/superMaster/index.gsp
<%@ page import="biz.nellemann.powerdns.SuperMaster" %>
<!DOCTYPE html>
<html>
<head>
    <g:set var="entityName" value="${message(code: 'superMaster.label', default: 'SuperMaster')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
    <meta name="layout" content="main">
    <r:require modules="bootstrap"/>
</head>

<body>

<!-- Breadcrumbs -->
<div class="row">
    <ol class="breadcrumb">
        <li class="active">SuperMasters</li>
    </ol>
</div>

<!-- Alerts and header -->
<div class="row">
    <g:if test="${flash.message}">
        <div class="alert alert-info" role="status">${flash.message}</div>
    </g:if>
</div>

<!-- Create new domain -->
<div class="row">
    <div class="text-info">
        <p><span class="glyphicon glyphicon-plus-sign"></span> <g:link action="create">Create a new SuperMaster</g:link></p>
    </div>
</div>


<!-- List of domains -->
<div class="row">
    <div class="table-responsive" id="listItems">
        <g:render template="list" />
    </div>
    <div>
        <g:paginate total="${smInstanceCount ?: 0}" class="pagination-sm" />
    </div>
</div>

<div class="row">
    <div class="well well-lg">
        Before a SuperMaster notification succeeds, the following conditions must be met:
        <ul>
            <li>The supermaster must carry a SOA record for the notified domain</li>
            <li>The supermaster IP must be present in our list above</li>
            <li>The set of NS records for the domain, as retrieved by the slave from the supermaster,
            must include the hostname that goes with the IP address listed above.</li>
        </ul>
    </div>
    <div class="well well-lg">
        To enable the use of PowerDNS SuperMasters, you must also enable slave operations (slave=yes) in your pdns.conf configuration file.
    </div>
</div>


</body>
</html>